server:
  port: 8083

spring:
  application:
    name: FRAUD-SERVICE


  kafka:
      bootstrap-servers: localhost:9092

      consumer:
        group-id: fraud-group

        auto-offset-reset: latest

        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:5432/insurance_system
    username: postgres
    password: Parth@1301

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.apache.kafka: WARN


